import { PrismaClient } from '@prisma/client';
import * as filterConfigData from './seed-data/filter-config.json';

const prisma = new PrismaClient();

// Apple products data
const appleProducts = [
  // iPhone 15 系列
  {
    id: 'iphone_15_pro_max',
    name: 'iPhone 15 Pro Max',
    company: 'Apple',
    category: '手机',
    imageUrl: 'https://via.placeholder.com/300x300?text=iPhone+15+Pro+Max',
    price: 9999,
    releaseDate: new Date('2023-09-22'),
    description: 'iPhone 15 Pro Max，搭载3纳米A17 Pro芯片，钛金属设计',
    // 核心筛选字段
    productLine: '旗舰',
    processor: 'A17 Pro',
    ram: '8GB',
    storage: '256GB',
    screenSize: '6.7英寸',
    // 详细数据
    specs: {
      colors: ['原色钛金属', '白色钛金属', '蓝色钛金属', '黑色钛金属'],
      camera: '48MP主摄 + 12MP超广角 + 12MP 5x长焦',
      battery: '4422mAh',
      features: ['防水', '无线', '快充', '高分辨率', '钛金属边框', '动态岛'],
    },
    specifications: {
      '屏幕尺寸': '6.7英寸',
      '分辨率': '2796 x 1290',
      '处理器': 'A17 Pro (3nm)',
      '内存': '8GB',
      '存储': '256GB',
      '主摄像头': '48MP',
      '超广角': '12MP',
      '长焦': '12MP (5x)',
      '前置摄像头': '12MP',
      '电池容量': '4422mAh',
      '重量': '221g',
      '厚度': '8.25mm',
      '防水等级': 'IP68',
      '操作系统': 'iOS 17',
      '屏幕刷新率': '120Hz ProMotion',
      '峰值亮度': '2000尼特',
      '充电功率': '27W有线 + 15W无线',
    },
  },
  {
    id: 'iphone_15_pro',
    name: 'iPhone 15 Pro',
    company: 'Apple',
    category: '手机',
    imageUrl: 'https://via.placeholder.com/300x300?text=iPhone+15+Pro',
    price: 7999,
    releaseDate: new Date('2023-09-22'),
    specs: {
      productLine: '旗舰',
      colors: ['原色钛金属', '白色钛金属', '蓝色钛金属', '黑色钛金属'],
      screen: '6.1英寸',
      processor: 'A17 Pro',
      ram: '8GB',
      storage: '128GB',
      camera: '48MP主摄 + 12MP超广角 + 12MP 3x长焦',
      battery: '3274mAh',
      features: ['防水', '无线', '快充', '高分辨率', '钛金属边框', '动态岛'],
    },
    description: 'iPhone 15 Pro，搭载3纳米A17 Pro芯片，钛金属设计',
    specifications: {
      '屏幕尺寸': '6.1英寸',
      '分辨率': '2556 x 1179',
      '处理器': 'A17 Pro (3nm)',
      '内存': '8GB',
      '存储': '128GB',
      '主摄像头': '48MP',
      '超广角': '12MP',
      '长焦': '12MP (3x)',
      '前置摄像头': '12MP',
      '电池容量': '3274mAh',
      '重量': '187g',
      '厚度': '8.25mm',
      '防水等级': 'IP68',
      '操作系统': 'iOS 17',
      '屏幕刷新率': '120Hz ProMotion',
      '峰值亮度': '2000尼特',
      '充电功率': '27W有线 + 15W无线',
    },
  },
  {
    id: 'iphone_15_plus',
    name: 'iPhone 15 Plus',
    company: 'Apple',
    category: '手机',
    imageUrl: 'https://via.placeholder.com/300x300?text=iPhone+15+Plus',
    price: 6999,
    releaseDate: new Date('2023-09-22'),
    specs: {
      productLine: '中端',
      colors: ['黑色', '蓝色', '绿色', '黄色', '粉色'],
      screen: '6.7英寸',
      processor: 'A16 Bionic',
      ram: '6GB',
      storage: '128GB',
      camera: '48MP主摄 + 12MP超广角',
      battery: '4383mAh',
      features: ['防水', '无线', '快充', '高分辨率', '动态岛'],
    },
    description: 'iPhone 15 Plus，6.7英寸大屏，动态岛设计',
    specifications: {
      '屏幕尺寸': '6.7英寸',
      '分辨率': '2796 x 1290',
      '处理器': 'A16 Bionic',
      '内存': '6GB',
      '存储': '128GB',
      '主摄像头': '48MP',
      '超广角': '12MP',
      '前置摄像头': '12MP',
      '电池容量': '4383mAh',
      '重量': '201g',
      '厚度': '7.80mm',
      '防水等级': 'IP68',
      '操作系统': 'iOS 17',
      '屏幕刷新率': '60Hz',
      '峰值亮度': '2000尼特',
      '充电功率': '27W有线 + 15W无线',
    },
  },
  {
    id: 'iphone_15',
    name: 'iPhone 15',
    company: 'Apple',
    category: '手机',
    imageUrl: 'https://via.placeholder.com/300x300?text=iPhone+15',
    price: 5999,
    releaseDate: new Date('2023-09-22'),
    specs: {
      productLine: '中端',
      colors: ['黑色', '蓝色', '绿色', '黄色', '粉色'],
      screen: '6.1英寸',
      processor: 'A16 Bionic',
      ram: '6GB',
      storage: '128GB',
      camera: '48MP主摄 + 12MP超广角',
      battery: '3349mAh',
      features: ['防水', '无线', '快充', '高分辨率', '动态岛'],
    },
    description: 'iPhone 15，全新动态岛设计，48MP相机系统',
    specifications: {
      '屏幕尺寸': '6.1英寸',
      '分辨率': '2556 x 1179',
      '处理器': 'A16 Bionic',
      '内存': '6GB',
      '存储': '128GB',
      '主摄像头': '48MP',
      '超广角': '12MP',
      '前置摄像头': '12MP',
      '电池容量': '3349mAh',
      '重量': '171g',
      '厚度': '7.80mm',
      '防水等级': 'IP68',
      '操作系统': 'iOS 17',
      '屏幕刷新率': '60Hz',
      '峰值亮度': '2000尼特',
      '充电功率': '20W有线 + 15W无线',
    },
  },
  // MacBook 系列
  {
    id: 'macbook_pro_16_m3_max',
    name: 'MacBook Pro 16" (M3 Max)',
    company: 'Apple',
    category: '笔记本',
    imageUrl: 'https://via.placeholder.com/300x300?text=MacBook+Pro+16+M3+Max',
    price: 25999,
    releaseDate: new Date('2023-11-07'),
    specs: {
      productLine: '旗舰',
      colors: ['深空灰色', '银色'],
      screen: '16.2英寸',
      processor: 'M3 Max',
      ram: '36GB',
      storage: '1TB SSD',
      graphics: '40核GPU',
      battery: '100Wh',
      features: ['高分辨率', '背光', '触屏', 'MiniLED', 'ProMotion 120Hz'],
    },
    description: 'MacBook Pro 16英寸，搭载M3 Max芯片，专业性能巅峰',
    specifications: {
      '屏幕尺寸': '16.2英寸',
      '分辨率': '3456 x 2234',
      '处理器': 'Apple M3 Max (16核CPU)',
      '内存': '36GB统一内存',
      '存储': '1TB SSD',
      '显卡': '40核GPU',
      '电池容量': '100Wh',
      '电池续航': '22小时',
      '重量': '2.16kg',
      '厚度': '16.8mm',
      '接口': '3×Thunderbolt 4 + HDMI + SD卡槽 + MagSafe 3',
      '操作系统': 'macOS Sonoma',
      '屏幕刷新率': '120Hz ProMotion',
      '峰值亮度': '1600尼特 (HDR)',
      '音频': '6扬声器系统',
      '摄像头': '1080p FaceTime',
    },
  },
  {
    id: 'macbook_air_13_m3',
    name: 'MacBook Air 13" (M3)',
    company: 'Apple',
    category: '笔记本',
    imageUrl: 'https://via.placeholder.com/300x300?text=MacBook+Air+13+M3',
    price: 8999,
    releaseDate: new Date('2024-03-04'),
    specs: {
      productLine: '中端',
      colors: ['午夜色', '星光色', '深空灰色', '银色'],
      screen: '13.6英寸',
      processor: 'M3',
      ram: '8GB',
      storage: '256GB SSD',
      graphics: '10核GPU',
      battery: '52.6Wh',
      features: ['高分辨率', '背光', '超薄'],
    },
    description: 'MacBook Air 13英寸，搭载M3芯片，轻薄便携新选择',
    specifications: {
      '屏幕尺寸': '13.6英寸',
      '分辨率': '2560 x 1664',
      '处理器': 'Apple M3 (8核CPU)',
      '内存': '8GB统一内存',
      '存储': '256GB SSD',
      '显卡': '10核GPU',
      '电池容量': '52.6Wh',
      '电池续航': '18小时',
      '重量': '1.24kg',
      '厚度': '11.3mm',
      '接口': '2×Thunderbolt 4 + MagSafe 3',
      '操作系统': 'macOS Sonoma',
      '屏幕刷新率': '60Hz',
      '峰值亮度': '500尼特',
      '音频': '4扬声器系统',
      '摄像头': '1080p FaceTime',
    },
  },
  // iPad 系列
  {
    id: 'ipad_pro_13_m4',
    name: 'iPad Pro 13" (M4)',
    company: 'Apple',
    category: '平板',
    imageUrl: 'https://via.placeholder.com/300x300?text=iPad+Pro+13+M4',
    price: 10999,
    releaseDate: new Date('2024-05-15'),
    specs: {
      productLine: '旗舰',
      colors: ['深空灰色', '银色'],
      screen: '13英寸',
      processor: 'M4',
      ram: '16GB',
      storage: '512GB',
      camera: '12MP主摄 + 10MP超广角',
      battery: '10340mAh',
      features: ['防水', '无线', '快充', '高分辨率', '触屏', 'ProMotion 120Hz', 'Tandem OLED'],
    },
    description: 'iPad Pro 13英寸，史上最薄iPad，搭载M4芯片',
    specifications: {
      '屏幕尺寸': '13英寸',
      '分辨率': '2752 x 2064',
      '处理器': 'Apple M4 (10核CPU)',
      '内存': '16GB',
      '存储': '512GB',
      '主摄像头': '12MP',
      '超广角': '10MP',
      '前置摄像头': '12MP TrueDepth',
      '电池容量': '10340mAh',
      '电池续航': '10小时',
      '重量': '579g',
      '厚度': '5.1mm',
      '操作系统': 'iPadOS 17',
      '屏幕刷新率': '120Hz ProMotion',
      '峰值亮度': '1600尼特 (HDR)',
      '充电功率': '45W快充',
      '连接': 'Thunderbolt 4',
    },
  },
  {
    id: 'ipad_air_11_m2',
    name: 'iPad Air 11" (M2)',
    company: 'Apple',
    category: '平板',
    imageUrl: 'https://via.placeholder.com/300x300?text=iPad+Air+11+M2',
    price: 4799,
    releaseDate: new Date('2024-05-15'),
    specs: {
      productLine: '中端',
      colors: ['深空灰色', '星光色', '紫色', '蓝色'],
      screen: '11英寸',
      processor: 'M2',
      ram: '8GB',
      storage: '128GB',
      camera: '12MP主摄',
      battery: '7606mAh',
      features: ['无线', '快充', '高分辨率', '触屏'],
    },
    description: 'iPad Air 11英寸，搭载M2芯片，轻薄多彩新选择',
    specifications: {
      '屏幕尺寸': '11英寸',
      '分辨率': '2360 x 1640',
      '处理器': 'Apple M2 (8核CPU)',
      '内存': '8GB',
      '存储': '128GB',
      '主摄像头': '12MP',
      '前置摄像头': '12MP TrueDepth',
      '电池容量': '7606mAh',
      '电池续航': '10小时',
      '重量': '461g',
      '厚度': '6.1mm',
      '操作系统': 'iPadOS 17',
      '屏幕刷新率': '60Hz',
      '峰值亮度': '500尼特',
      '充电功率': '20W快充',
      '连接': 'USB-C',
    },
  },
  // Apple Watch 系列
  {
    id: 'apple_watch_series_9_45mm',
    name: 'Apple Watch Series 9 (45mm)',
    company: 'Apple',
    category: '智能手表',
    imageUrl: 'https://via.placeholder.com/300x300?text=Apple+Watch+S9+45mm',
    price: 3199,
    releaseDate: new Date('2023-09-22'),
    specs: {
      productLine: '旗舰',
      colors: ['午夜色', '星光色', '银色', '红色'],
      screen: '1.9英寸',
      processor: 'S9',
      storage: '64GB',
      battery: '308mAh',
      features: ['防水', '无线', '快充', '高分辨率', '触屏', '心率监测', 'ECG'],
    },
    description: 'Apple Watch Series 9，双指互点手势，全新S9芯片',
    specifications: {
      '屏幕尺寸': '1.9英寸',
      '分辨率': '484 x 396',
      '处理器': 'Apple S9',
      '存储': '64GB',
      '传感器': '心率/ECG/血氧/加速度/陀螺仪/指南针/高度计',
      '电池容量': '308mAh',
      '电池续航': '18小时',
      '重量': '38.7g',
      '厚度': '10.7mm',
      '防水等级': '50米防水',
      '操作系统': 'watchOS 10',
      '屏幕刷新率': '60Hz LTPO',
      '峰值亮度': '2000尼特',
      '充电功率': '快充',
      '连接': '蓝牙5.3 + Wi-Fi',
    },
  },
  {
    id: 'apple_watch_ultra_2',
    name: 'Apple Watch Ultra 2',
    company: 'Apple',
    category: '智能手表',
    imageUrl: 'https://via.placeholder.com/300x300?text=Apple+Watch+Ultra+2',
    price: 6499,
    releaseDate: new Date('2023-09-22'),
    specs: {
      productLine: '旗舰',
      colors: ['钛金属'],
      screen: '1.92英寸',
      processor: 'S9',
      storage: '64GB',
      battery: '542mAh',
      features: ['防水', '无线', '快充', '高分辨率', '触屏', '心率监测', 'ECG', '深度计', '温度传感器'],
    },
    description: 'Apple Watch Ultra 2，极限运动专用，100米防水',
    specifications: {
      '屏幕尺寸': '1.92英寸',
      '分辨率': '502 x 410',
      '处理器': 'Apple S9',
      '存储': '64GB',
      '传感器': '心率/ECG/血氧/加速度/陀螺仪/指南针/高度计/深度计/温度',
      '电池容量': '542mAh',
      '电池续航': '36小时 (低功耗72小时)',
      '重量': '61.4g',
      '厚度': '14.4mm',
      '防水等级': '100米防水',
      '操作系统': 'watchOS 10',
      '屏幕刷新率': '60Hz LTPO',
      '峰值亮度': '3000尼特',
      '充电功率': '快充',
      '连接': '蓝牙5.3 + Wi-Fi + 双频GPS',
    },
  },
  // AirPods 系列
  {
    id: 'airpods_pro_2_usbc',
    name: 'AirPods Pro (第2代 USB-C)',
    company: 'Apple',
    category: '耳机',
    imageUrl: 'https://via.placeholder.com/300x300?text=AirPods+Pro+2+USB-C',
    price: 1899,
    releaseDate: new Date('2023-09-22'),
    specs: {
      productLine: '旗舰',
      colors: ['白色'],
      processor: 'H2',
      battery: '6小时',
      features: ['防水', '无线', '快充', '主动降噪', '空间音频', '自适应降噪'],
    },
    description: 'AirPods Pro 第2代，H2芯片，自适应降噪，USB-C接口',
    specifications: {
      '芯片': 'Apple H2',
      '降噪': '主动降噪 + 自适应降噪',
      '通透模式': '自适应通透',
      '空间音频': '支持动态头部追踪',
      '自适应音频': '支持',
      '续航时间': '6小时 (降噪开启)',
      '充电盒续航': '30小时',
      '充电接口': 'USB-C',
      '防水等级': 'IPX4',
      '重量': '5.3g (单耳)',
      '充电盒重量': '50.8g',
      '连接': '蓝牙5.3',
      '特殊功能': 'Find My精确查找 + MagSafe充电',
    },
  },
  {
    id: 'airpods_max',
    name: 'AirPods Max',
    company: 'Apple',
    category: '耳机',
    imageUrl: 'https://via.placeholder.com/300x300?text=AirPods+Max',
    price: 4399,
    releaseDate: new Date('2020-12-15'),
    specs: {
      productLine: '旗舰',
      colors: ['银色', '深空灰色', '天蓝色', '绿色', '粉色'],
      processor: 'H1',
      battery: '20小时',
      features: ['无线', '主动降噪', '空间音频', '高保真'],
    },
    description: 'AirPods Max，头戴式旗舰，40mm动圈单元，高保真音质',
    specifications: {
      '芯片': '双H1芯片',
      '降噪': '主动降噪',
      '通透模式': '支持',
      '空间音频': '支持动态头部追踪',
      '续航时间': '20小时 (降噪开启)',
      '充电接口': 'Lightning',
      '驱动单元': '40mm动圈',
      '重量': '384.8g',
      '材质': '铝合金 + 不锈钢 + 记忆海绵',
      '连接': '蓝牙5.0',
      '特殊功能': '数字旋钮 + 自适应均衡',
    },
  },
  
  // iPhone 14 系列
  {
    id: 'iphone_14_pro_max',
    name: 'iPhone 14 Pro Max',
    company: 'Apple',
    category: '手机',
    imageUrl: 'https://via.placeholder.com/300x300?text=iPhone+14+Pro+Max',
    price: 8999,
    releaseDate: new Date('2022-09-16'),
    description: 'iPhone 14 Pro Max，首款配备动态岛设计',
    productLine: '旗舰',
    processor: 'A16 Bionic',
    ram: '6GB',
    storage: '128GB',
    screenSize: '6.7英寸',
    specs: {
      colors: ['深空黑色', '银色', '金色', '暗紫色'],
      camera: '48MP主摄 + 12MP超广角 + 12MP 3x长焦',
      battery: '4323mAh',
      features: ['防水', '无线', '快充', '高分辨率', '动态岛', '息屏显示'],
    },
    specifications: {
      '屏幕尺寸': '6.7英寸',
      '分辨率': '2796 x 1290',
      '处理器': 'A16 Bionic',
      '内存': '6GB',
      '存储': '128GB',
      '主摄像头': '48MP',
      '超广角': '12MP',
      '长焦': '12MP (3x)',
      '前置摄像头': '12MP',
      '电池容量': '4323mAh',
      '重量': '240g',
      '厚度': '7.85mm',
      '防水等级': 'IP68',
      '操作系统': 'iOS 16',
      '屏幕刷新率': '120Hz ProMotion',
      '峰值亮度': '2000尼特',
      '充电功率': '27W有线 + 15W无线',
    },
  },
  {
    id: 'iphone_14_pro',
    name: 'iPhone 14 Pro',
    company: 'Apple',
    category: '手机',
    imageUrl: 'https://via.placeholder.com/300x300?text=iPhone+14+Pro',
    price: 7999,
    releaseDate: new Date('2022-09-16'),
    description: 'iPhone 14 Pro，48MP主摄，动态岛设计',
    productLine: '旗舰',
    processor: 'A16 Bionic',
    ram: '6GB',
    storage: '128GB',
    screenSize: '6.1英寸',
    specs: {
      colors: ['深空黑色', '银色', '金色', '暗紫色'],
      camera: '48MP主摄 + 12MP超广角 + 12MP 3x长焦',
      battery: '3200mAh',
      features: ['防水', '无线', '快充', '高分辨率', '动态岛'],
    },
    specifications: {
      '屏幕尺寸': '6.1英寸',
      '分辨率': '2556 x 1179',
      '处理器': 'A16 Bionic',
      '内存': '6GB',
      '存储': '128GB',
      '主摄像头': '48MP',
      '超广角': '12MP',
      '长焦': '12MP (3x)',
      '前置摄像头': '12MP',
      '电池容量': '3200mAh',
      '重量': '206g',
      '厚度': '7.85mm',
      '防水等级': 'IP68',
      '操作系统': 'iOS 16',
      '屏幕刷新率': '120Hz ProMotion',
      '峰值亮度': '2000尼特',
      '充电功率': '27W有线 + 15W无线',
    },
  },
  {
    id: 'iphone_14_plus',
    name: 'iPhone 14 Plus',
    company: 'Apple',
    category: '手机',
    imageUrl: 'https://via.placeholder.com/300x300?text=iPhone+14+Plus',
    price: 6999,
    releaseDate: new Date('2022-10-07'),
    description: 'iPhone 14 Plus，6.7英寸大屏',
    productLine: '中端',
    processor: 'A15 Bionic',
    ram: '6GB',
    storage: '128GB',
    screenSize: '6.7英寸',
    specs: {
      colors: ['午夜色', '星光色', '紫色', '红色', '蓝色'],
      camera: '12MP主摄 + 12MP超广角',
      battery: '4325mAh',
      features: ['防水', '无线', '快充'],
    },
    specifications: {
      '屏幕尺寸': '6.7英寸',
      '分辨率': '2778 x 1284',
      '处理器': 'A15 Bionic',
      '内存': '6GB',
      '存储': '128GB',
      '主摄像头': '12MP',
      '超广角': '12MP',
      '前置摄像头': '12MP',
      '电池容量': '4325mAh',
      '重量': '203g',
      '厚度': '7.80mm',
      '防水等级': 'IP68',
      '操作系统': 'iOS 16',
      '屏幕刷新率': '60Hz',
      '峰值亮度': '1200尼特',
      '充电功率': '20W有线 + 15W无线',
    },
  },
  {
    id: 'iphone_14',
    name: 'iPhone 14',
    company: 'Apple',
    category: '手机',
    imageUrl: 'https://via.placeholder.com/300x300?text=iPhone+14',
    price: 5999,
    releaseDate: new Date('2022-09-16'),
    description: 'iPhone 14，经典设计，可靠性能',
    productLine: '中端',
    processor: 'A15 Bionic',
    ram: '6GB',
    storage: '128GB',
    screenSize: '6.1英寸',
    specs: {
      colors: ['午夜色', '星光色', '紫色', '红色', '蓝色'],
      camera: '12MP主摄 + 12MP超广角',
      battery: '3279mAh',
      features: ['防水', '无线', '快充'],
    },
    specifications: {
      '屏幕尺寸': '6.1英寸',
      '分辨率': '2532 x 1170',
      '处理器': 'A15 Bionic',
      '内存': '6GB',
      '存储': '128GB',
      '主摄像头': '12MP',
      '超广角': '12MP',
      '前置摄像头': '12MP',
      '电池容量': '3279mAh',
      '重量': '172g',
      '厚度': '7.80mm',
      '防水等级': 'IP68',
      '操作系统': 'iOS 16',
      '屏幕刷新率': '60Hz',
      '峰值亮度': '1200尼特',
      '充电功率': '20W有线 + 15W无线',
    },
  },
  
  // iPhone 13 系列
  {
    id: 'iphone_13_pro_max',
    name: 'iPhone 13 Pro Max',
    company: 'Apple',
    category: '手机',
    imageUrl: 'https://via.placeholder.com/300x300?text=iPhone+13+Pro+Max',
    price: 8999,
    releaseDate: new Date('2021-09-24'),
    description: 'iPhone 13 Pro Max，首款ProMotion显示屏',
    productLine: '旗舰',
    processor: 'A15 Bionic',
    ram: '6GB',
    storage: '128GB',
    screenSize: '6.7英寸',
    specs: {
      colors: ['石墨色', '金色', '银色', '远峰蓝色'],
      camera: '12MP主摄 + 12MP超广角 + 12MP 3x长焦',
      battery: '4352mAh',
      features: ['防水', '无线', '快充', '高分辨率'],
    },
    specifications: {
      '屏幕尺寸': '6.7英寸',
      '分辨率': '2778 x 1284',
      '处理器': 'A15 Bionic',
      '内存': '6GB',
      '存储': '128GB',
      '主摄像头': '12MP',
      '超广角': '12MP',
      '长焦': '12MP (3x)',
      '前置摄像头': '12MP',
      '电池容量': '4352mAh',
      '重量': '238g',
      '厚度': '7.65mm',
      '防水等级': 'IP68',
      '操作系统': 'iOS 15',
      '屏幕刷新率': '120Hz ProMotion',
      '峰值亮度': '1200尼特',
      '充电功率': '27W有线 + 15W无线',
    },
  },
  {
    id: 'iphone_13_pro',
    name: 'iPhone 13 Pro',
    company: 'Apple',
    category: '手机',
    imageUrl: 'https://via.placeholder.com/300x300?text=iPhone+13+Pro',
    price: 7999,
    releaseDate: new Date('2021-09-24'),
    description: 'iPhone 13 Pro，配备ProMotion自适应刷新率',
    productLine: '旗舰',
    processor: 'A15 Bionic',
    ram: '6GB',
    storage: '128GB',
    screenSize: '6.1英寸',
    specs: {
      colors: ['石墨色', '金色', '银色', '远峰蓝色'],
      camera: '12MP主摄 + 12MP超广角 + 12MP 3x长焦',
      battery: '3095mAh',
      features: ['防水', '无线', '快充', '高分辨率'],
    },
    specifications: {
      '屏幕尺寸': '6.1英寸',
      '分辨率': '2532 x 1170',
      '处理器': 'A15 Bionic',
      '内存': '6GB',
      '存储': '128GB',
      '主摄像头': '12MP',
      '超广角': '12MP',
      '长焦': '12MP (3x)',
      '前置摄像头': '12MP',
      '电池容量': '3095mAh',
      '重量': '203g',
      '厚度': '7.65mm',
      '防水等级': 'IP68',
      '操作系统': 'iOS 15',
      '屏幕刷新率': '120Hz ProMotion',
      '峰值亮度': '1200尼特',
      '充电功率': '27W有线 + 15W无线',
    },
  },
  
  // MacBook Pro M3 系列
  {
    id: 'macbook_pro_16_m3_pro',
    name: 'MacBook Pro 16" (M3 Pro)',
    company: 'Apple',
    category: '笔记本',
    imageUrl: 'https://via.placeholder.com/300x300?text=MacBook+Pro+16+M3+Pro',
    price: 19999,
    releaseDate: new Date('2023-11-07'),
    description: 'MacBook Pro 16英寸，M3 Pro芯片，专业性能',
    productLine: '旗舰',
    processor: 'M3 Pro',
    ram: '18GB',
    storage: '512GB SSD',
    screenSize: '16.2英寸',
    specs: {
      colors: ['深空灰色', '银色'],
      graphics: '18核GPU',
      battery: '100Wh',
      features: ['高分辨率', '背光', 'MiniLED', 'ProMotion 120Hz'],
    },
    specifications: {
      '屏幕尺寸': '16.2英寸',
      '分辨率': '3456 x 2234',
      '处理器': 'Apple M3 Pro (12核CPU)',
      '内存': '18GB统一内存',
      '存储': '512GB SSD',
      '显卡': '18核GPU',
      '电池容量': '100Wh',
      '电池续航': '22小时',
      '重量': '2.14kg',
      '厚度': '16.8mm',
      '接口': '3×Thunderbolt 4 + HDMI + SD卡槽 + MagSafe 3',
      '操作系统': 'macOS Sonoma',
      '屏幕刷新率': '120Hz ProMotion',
      '峰值亮度': '1600尼特 (HDR)',
      '音频': '6扬声器系统',
      '摄像头': '1080p FaceTime',
    },
  },
  {
    id: 'macbook_pro_14_m3_max',
    name: 'MacBook Pro 14" (M3 Max)',
    company: 'Apple',
    category: '笔记本',
    imageUrl: 'https://via.placeholder.com/300x300?text=MacBook+Pro+14+M3+Max',
    price: 21999,
    releaseDate: new Date('2023-11-07'),
    description: 'MacBook Pro 14英寸，M3 Max芯片，极致性能',
    productLine: '旗舰',
    processor: 'M3 Max',
    ram: '36GB',
    storage: '1TB SSD',
    screenSize: '14.2英寸',
    specs: {
      colors: ['深空灰色', '银色'],
      graphics: '30核GPU',
      battery: '70Wh',
      features: ['高分辨率', '背光', 'MiniLED', 'ProMotion 120Hz'],
    },
    specifications: {
      '屏幕尺寸': '14.2英寸',
      '分辨率': '3024 x 1964',
      '处理器': 'Apple M3 Max (14核CPU)',
      '内存': '36GB统一内存',
      '存储': '1TB SSD',
      '显卡': '30核GPU',
      '电池容量': '70Wh',
      '电池续航': '18小时',
      '重量': '1.61kg',
      '厚度': '15.5mm',
      '接口': '3×Thunderbolt 4 + HDMI + SD卡槽 + MagSafe 3',
      '操作系统': 'macOS Sonoma',
      '屏幕刷新率': '120Hz ProMotion',
      '峰值亮度': '1600尼特 (HDR)',
      '音频': '6扬声器系统',
      '摄像头': '1080p FaceTime',
    },
  },
  {
    id: 'macbook_pro_14_m3_pro',
    name: 'MacBook Pro 14" (M3 Pro)',
    company: 'Apple',
    category: '笔记本',
    imageUrl: 'https://via.placeholder.com/300x300?text=MacBook+Pro+14+M3+Pro',
    price: 15999,
    releaseDate: new Date('2023-11-07'),
    description: 'MacBook Pro 14英寸，M3 Pro芯片，专业创作',
    productLine: '旗舰',
    processor: 'M3 Pro',
    ram: '18GB',
    storage: '512GB SSD',
    screenSize: '14.2英寸',
    specs: {
      colors: ['深空灰色', '银色'],
      graphics: '14核GPU',
      battery: '70Wh',
      features: ['高分辨率', '背光', 'MiniLED', 'ProMotion 120Hz'],
    },
    specifications: {
      '屏幕尺寸': '14.2英寸',
      '分辨率': '3024 x 1964',
      '处理器': 'Apple M3 Pro (11核CPU)',
      '内存': '18GB统一内存',
      '存储': '512GB SSD',
      '显卡': '14核GPU',
      '电池容量': '70Wh',
      '电池续航': '18小时',
      '重量': '1.55kg',
      '厚度': '15.5mm',
      '接口': '3×Thunderbolt 4 + HDMI + SD卡槽 + MagSafe 3',
      '操作系统': 'macOS Sonoma',
      '屏幕刷新率': '120Hz ProMotion',
      '峰值亮度': '1600尼特 (HDR)',
      '音频': '6扬声器系统',
      '摄像头': '1080p FaceTime',
    },
  },
  {
    id: 'macbook_pro_14_m3',
    name: 'MacBook Pro 14" (M3)',
    company: 'Apple',
    category: '笔记本',
    imageUrl: 'https://via.placeholder.com/300x300?text=MacBook+Pro+14+M3',
    price: 12999,
    releaseDate: new Date('2023-11-07'),
    description: 'MacBook Pro 14英寸，M3芯片，入门专业级',
    productLine: '中端',
    processor: 'M3',
    ram: '8GB',
    storage: '512GB SSD',
    screenSize: '14.2英寸',
    specs: {
      colors: ['深空灰色', '银色'],
      graphics: '10核GPU',
      battery: '70Wh',
      features: ['高分辨率', '背光', 'MiniLED', 'ProMotion 120Hz'],
    },
    specifications: {
      '屏幕尺寸': '14.2英寸',
      '分辨率': '3024 x 1964',
      '处理器': 'Apple M3 (8核CPU)',
      '内存': '8GB统一内存',
      '存储': '512GB SSD',
      '显卡': '10核GPU',
      '电池容量': '70Wh',
      '电池续航': '17小时',
      '重量': '1.55kg',
      '厚度': '15.5mm',
      '接口': '2×Thunderbolt 4 + HDMI + SD卡槽 + MagSafe 3',
      '操作系统': 'macOS Sonoma',
      '屏幕刷新率': '120Hz ProMotion',
      '峰值亮度': '1600尼特 (HDR)',
      '音频': '6扬声器系统',
      '摄像头': '1080p FaceTime',
    },
  },
  
  // MacBook Air M3/M2 系列
  {
    id: 'macbook_air_15_m3',
    name: 'MacBook Air 15" (M3)',
    company: 'Apple',
    category: '笔记本',
    imageUrl: 'https://via.placeholder.com/300x300?text=MacBook+Air+15+M3',
    price: 10499,
    releaseDate: new Date('2024-03-04'),
    description: 'MacBook Air 15英寸，M3芯片，大屏轻薄',
    productLine: '中端',
    processor: 'M3',
    ram: '8GB',
    storage: '256GB SSD',
    screenSize: '15.3英寸',
    specs: {
      colors: ['午夜色', '星光色', '深空灰色', '银色'],
      graphics: '10核GPU',
      battery: '66.5Wh',
      features: ['高分辨率', '背光', '超薄'],
    },
    specifications: {
      '屏幕尺寸': '15.3英寸',
      '分辨率': '2880 x 1864',
      '处理器': 'Apple M3 (8核CPU)',
      '内存': '8GB统一内存',
      '存储': '256GB SSD',
      '显卡': '10核GPU',
      '电池容量': '66.5Wh',
      '电池续航': '18小时',
      '重量': '1.51kg',
      '厚度': '11.5mm',
      '接口': '2×Thunderbolt 4 + MagSafe 3',
      '操作系统': 'macOS Sonoma',
      '屏幕刷新率': '60Hz',
      '峰值亮度': '500尼特',
      '音频': '6扬声器系统',
      '摄像头': '1080p FaceTime',
    },
  },
  {
    id: 'macbook_air_15_m2',
    name: 'MacBook Air 15" (M2)',
    company: 'Apple',
    category: '笔记本',
    imageUrl: 'https://via.placeholder.com/300x300?text=MacBook+Air+15+M2',
    price: 9999,
    releaseDate: new Date('2023-06-13'),
    description: 'MacBook Air 15英寸，首款大屏Air',
    productLine: '中端',
    processor: 'M2',
    ram: '8GB',
    storage: '256GB SSD',
    screenSize: '15.3英寸',
    specs: {
      colors: ['午夜色', '星光色', '深空灰色', '银色'],
      graphics: '10核GPU',
      battery: '66.5Wh',
      features: ['高分辨率', '背光', '超薄'],
    },
    specifications: {
      '屏幕尺寸': '15.3英寸',
      '分辨率': '2880 x 1864',
      '处理器': 'Apple M2 (8核CPU)',
      '内存': '8GB统一内存',
      '存储': '256GB SSD',
      '显卡': '10核GPU',
      '电池容量': '66.5Wh',
      '电池续航': '18小时',
      '重量': '1.51kg',
      '厚度': '11.5mm',
      '接口': '2×Thunderbolt 4 + MagSafe 3',
      '操作系统': 'macOS Ventura',
      '屏幕刷新率': '60Hz',
      '峰值亮度': '500尼特',
      '音频': '6扬声器系统',
      '摄像头': '1080p FaceTime',
    },
  },
  
  // iPad 系列
  {
    id: 'ipad_pro_11_m4',
    name: 'iPad Pro 11" (M4)',
    company: 'Apple',
    category: '平板',
    imageUrl: 'https://via.placeholder.com/300x300?text=iPad+Pro+11+M4',
    price: 8999,
    releaseDate: new Date('2024-05-15'),
    description: 'iPad Pro 11英寸，M4芯片，极致轻薄',
    productLine: '旗舰',
    processor: 'M4',
    ram: '8GB',
    storage: '256GB',
    screenSize: '11英寸',
    specs: {
      colors: ['深空灰色', '银色'],
      camera: '12MP主摄 + 10MP超广角',
      battery: '7538mAh',
      features: ['无线', '快充', '高分辨率', '触屏', 'ProMotion 120Hz', 'Tandem OLED'],
    },
    specifications: {
      '屏幕尺寸': '11英寸',
      '分辨率': '2420 x 1668',
      '处理器': 'Apple M4 (9核CPU)',
      '内存': '8GB',
      '存储': '256GB',
      '主摄像头': '12MP',
      '超广角': '10MP',
      '前置摄像头': '12MP TrueDepth',
      '电池容量': '7538mAh',
      '电池续航': '10小时',
      '重量': '444g',
      '厚度': '5.3mm',
      '操作系统': 'iPadOS 17',
      '屏幕刷新率': '120Hz ProMotion',
      '峰值亮度': '1600尼特 (HDR)',
      '充电功率': '35W快充',
      '连接': 'Thunderbolt 4',
    },
  },
  {
    id: 'ipad_air_13_m2',
    name: 'iPad Air 13" (M2)',
    company: 'Apple',
    category: '平板',
    imageUrl: 'https://via.placeholder.com/300x300?text=iPad+Air+13+M2',
    price: 6499,
    releaseDate: new Date('2024-05-15'),
    description: 'iPad Air 13英寸，首款大屏Air',
    productLine: '中端',
    processor: 'M2',
    ram: '8GB',
    storage: '128GB',
    screenSize: '13英寸',
    specs: {
      colors: ['深空灰色', '星光色', '紫色', '蓝色'],
      camera: '12MP主摄',
      battery: '10290mAh',
      features: ['无线', '快充', '高分辨率', '触屏'],
    },
    specifications: {
      '屏幕尺寸': '13英寸',
      '分辨率': '2732 x 2048',
      '处理器': 'Apple M2 (8核CPU)',
      '内存': '8GB',
      '存储': '128GB',
      '主摄像头': '12MP',
      '前置摄像头': '12MP TrueDepth',
      '电池容量': '10290mAh',
      '电池续航': '10小时',
      '重量': '617g',
      '厚度': '6.1mm',
      '操作系统': 'iPadOS 17',
      '屏幕刷新率': '60Hz',
      '峰值亮度': '500尼特',
      '充电功率': '20W快充',
      '连接': 'USB-C',
    },
  },
  {
    id: 'ipad_10th',
    name: 'iPad (第10代)',
    company: 'Apple',
    category: '平板',
    imageUrl: 'https://via.placeholder.com/300x300?text=iPad+10th',
    price: 3499,
    releaseDate: new Date('2022-10-26'),
    description: 'iPad 第10代，全新彩色设计',
    productLine: '入门',
    processor: 'A14 Bionic',
    ram: '4GB',
    storage: '64GB',
    screenSize: '10.9英寸',
    specs: {
      colors: ['银色', '蓝色', '粉色', '黄色'],
      camera: '12MP主摄',
      battery: '7606mAh',
      features: ['无线', '快充', '触屏'],
    },
    specifications: {
      '屏幕尺寸': '10.9英寸',
      '分辨率': '2360 x 1640',
      '处理器': 'Apple A14 Bionic',
      '内存': '4GB',
      '存储': '64GB',
      '主摄像头': '12MP',
      '前置摄像头': '12MP (横向)',
      '电池容量': '7606mAh',
      '电池续航': '10小时',
      '重量': '477g',
      '厚度': '7.0mm',
      '操作系统': 'iPadOS 16',
      '屏幕刷新率': '60Hz',
      '峰值亮度': '500尼特',
      '充电功率': '20W快充',
      '连接': 'USB-C',
    },
  },
  {
    id: 'ipad_mini_6',
    name: 'iPad mini (第6代)',
    company: 'Apple',
    category: '平板',
    imageUrl: 'https://via.placeholder.com/300x300?text=iPad+mini+6',
    price: 3999,
    releaseDate: new Date('2021-09-24'),
    description: 'iPad mini 第6代，小巧便携',
    productLine: '入门',
    processor: 'A15 Bionic',
    ram: '4GB',
    storage: '64GB',
    screenSize: '8.3英寸',
    specs: {
      colors: ['深空灰色', '粉色', '紫色', '星光色'],
      camera: '12MP主摄',
      battery: '5124mAh',
      features: ['无线', '快充', '触屏'],
    },
    specifications: {
      '屏幕尺寸': '8.3英寸',
      '分辨率': '2266 x 1488',
      '处理器': 'Apple A15 Bionic',
      '内存': '4GB',
      '存储': '64GB',
      '主摄像头': '12MP',
      '前置摄像头': '12MP',
      '电池容量': '5124mAh',
      '电池续航': '10小时',
      '重量': '293g',
      '厚度': '6.3mm',
      '操作系统': 'iPadOS 15',
      '屏幕刷新率': '60Hz',
      '峰值亮度': '500尼特',
      '充电功率': '20W快充',
      '连接': 'USB-C',
    },
  },
  
  // Apple Watch 系列
  {
    id: 'apple_watch_series_9_41mm',
    name: 'Apple Watch Series 9 (41mm)',
    company: 'Apple',
    category: '智能手表',
    imageUrl: 'https://via.placeholder.com/300x300?text=Apple+Watch+S9+41mm',
    price: 2999,
    releaseDate: new Date('2023-09-22'),
    description: 'Apple Watch Series 9，双指互点手势',
    productLine: '旗舰',
    processor: 'S9',
    ram: null,
    storage: '64GB',
    screenSize: '1.7英寸',
    specs: {
      colors: ['午夜色', '星光色', '银色', '红色'],
      battery: '274mAh',
      features: ['防水', '无线', '快充', '高分辨率', '触屏', '心率监测', 'ECG'],
    },
    specifications: {
      '屏幕尺寸': '1.7英寸',
      '分辨率': '430 x 352',
      '处理器': 'Apple S9',
      '存储': '64GB',
      '传感器': '心率/ECG/血氧/加速度/陀螺仪/指南针/高度计',
      '电池容量': '274mAh',
      '电池续航': '18小时',
      '重量': '32.0g',
      '厚度': '10.7mm',
      '防水等级': '50米防水',
      '操作系统': 'watchOS 10',
      '屏幕刷新率': '60Hz LTPO',
      '峰值亮度': '2000尼特',
      '充电功率': '快充',
      '连接': '蓝牙5.3 + Wi-Fi',
    },
  },
  {
    id: 'apple_watch_se_2_44mm',
    name: 'Apple Watch SE (第2代) 44mm',
    company: 'Apple',
    category: '智能手表',
    imageUrl: 'https://via.placeholder.com/300x300?text=Apple+Watch+SE+44mm',
    price: 1999,
    releaseDate: new Date('2022-09-16'),
    description: 'Apple Watch SE 第2代，经济实惠的智能手表',
    productLine: '中端',
    processor: 'S8',
    ram: null,
    storage: '32GB',
    screenSize: '1.78英寸',
    specs: {
      colors: ['午夜色', '星光色', '银色'],
      battery: '296mAh',
      features: ['防水', '无线', '快充', '触屏', '心率监测'],
    },
    specifications: {
      '屏幕尺寸': '1.78英寸',
      '分辨率': '448 x 368',
      '处理器': 'Apple S8',
      '存储': '32GB',
      '传感器': '心率/加速度/陀螺仪/指南针/高度计',
      '电池容量': '296mAh',
      '电池续航': '18小时',
      '重量': '32.9g',
      '厚度': '10.7mm',
      '防水等级': '50米防水',
      '操作系统': 'watchOS 9',
      '屏幕刷新率': '60Hz LTPO',
      '峰值亮度': '1000尼特',
      '充电功率': '快充',
      '连接': '蓝牙5.3 + Wi-Fi',
    },
  },
  {
    id: 'apple_watch_se_2_40mm',
    name: 'Apple Watch SE (第2代) 40mm',
    company: 'Apple',
    category: '智能手表',
    imageUrl: 'https://via.placeholder.com/300x300?text=Apple+Watch+SE+40mm',
    price: 1799,
    releaseDate: new Date('2022-09-16'),
    description: 'Apple Watch SE 第2代 40mm，小巧实惠',
    productLine: '中端',
    processor: 'S8',
    ram: null,
    storage: '32GB',
    screenSize: '1.57英寸',
    specs: {
      colors: ['午夜色', '星光色', '银色'],
      battery: '245mAh',
      features: ['防水', '无线', '快充', '触屏', '心率监测'],
    },
    specifications: {
      '屏幕尺寸': '1.57英寸',
      '分辨率': '394 x 324',
      '处理器': 'Apple S8',
      '存储': '32GB',
      '传感器': '心率/加速度/陀螺仪/指南针/高度计',
      '电池容量': '245mAh',
      '电池续航': '18小时',
      '重量': '26.4g',
      '厚度': '10.7mm',
      '防水等级': '50米防水',
      '操作系统': 'watchOS 9',
      '屏幕刷新率': '60Hz LTPO',
      '峰值亮度': '1000尼特',
      '充电功率': '快充',
      '连接': '蓝牙5.3 + Wi-Fi',
    },
  },
  
  // AirPods 系列
  {
    id: 'airpods_pro_2',
    name: 'AirPods Pro (第2代)',
    company: 'Apple',
    category: '耳机',
    imageUrl: 'https://via.placeholder.com/300x300?text=AirPods+Pro+2',
    price: 1899,
    releaseDate: new Date('2022-09-23'),
    description: 'AirPods Pro 第2代，H2芯片，主动降噪',
    productLine: '旗舰',
    processor: 'H2',
    ram: null,
    storage: null,
    screenSize: null,
    specs: {
      colors: ['白色'],
      battery: '6小时',
      features: ['防水', '无线', '快充', '主动降噪', '空间音频'],
    },
    specifications: {
      '芯片': 'Apple H2',
      '降噪': '主动降噪 + 自适应降噪',
      '通透模式': '自适应通透',
      '空间音频': '支持动态头部追踪',
      '自适应音频': '支持',
      '续航时间': '6小时 (降噪开启)',
      '充电盒续航': '30小时',
      '充电接口': 'Lightning',
      '防水等级': 'IPX4',
      '重量': '5.3g (单耳)',
      '充电盒重量': '50.8g',
      '连接': '蓝牙5.3',
      '特殊功能': 'Find My精确查找 + MagSafe充电',
    },
  },
  {
    id: 'airpods_3',
    name: 'AirPods (第3代)',
    company: 'Apple',
    category: '耳机',
    imageUrl: 'https://via.placeholder.com/300x300?text=AirPods+3',
    price: 1399,
    releaseDate: new Date('2021-10-26'),
    description: 'AirPods 第3代，全新设计，空间音频',
    productLine: '中端',
    processor: 'H1',
    ram: null,
    storage: null,
    screenSize: null,
    specs: {
      colors: ['白色'],
      battery: '6小时',
      features: ['防水', '无线', '快充', '空间音频'],
    },
    specifications: {
      '芯片': 'Apple H1',
      '空间音频': '支持动态头部追踪',
      '续航时间': '6小时',
      '充电盒续航': '30小时',
      '充电接口': 'Lightning',
      '防水等级': 'IPX4',
      '重量': '4.28g (单耳)',
      '充电盒重量': '37.91g',
      '连接': '蓝牙5.0',
      '特殊功能': 'MagSafe充电',
    },
  },
];

async function main() {
  console.log('Start seeding...');

  // Clear existing data
  await prisma.product.deleteMany();
  await prisma.filterConfig.deleteMany();

  // Seed filter configuration
  console.log('Seeding filter configuration...');
  await prisma.filterConfig.create({
    data: {
      filterTree: filterConfigData.filterTree,
      comparisonModes: filterConfigData.comparisonModes,
    },
  });

  // Seed products
  console.log('Seeding products...');
  for (const product of appleProducts) {
    await prisma.product.create({
      data: product,
    });
  }

  console.log(`Seeded ${appleProducts.length} products`);
  console.log('Seeding complete!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

