# /.github/workflows/release.yml

name: Praxis CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # --- Job 1: CI 验证 (构建和测试) ---
  # 这个 Job 保持不变，在所有 push 和 PR 时运行
  ci:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install
      - name: Lint, Typecheck, Test, Build
        run: |
          pnpm lint
          pnpm typecheck
          pnpm test
          pnpm build

  # --- Job 2: 发布 (只在 main 分支且有版本更新时发布) ---
  release:
    name: Release to NPM
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: ci
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # 需要获取完整历史记录，以便 Changesets 能正确对比版本
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org/"

      - name: Install Dependencies
        run: pnpm install

      # 关键：使用 Changesets Action 来自动化版本和发布流程
      - name: Create Release
        id: changesets
        uses: changesets/action@v1
        with:
          # 这个命令会检查是否存在 changeset 文件。
          # 如果存在，它会自动执行版本提升、更新日志、推送 commit，然后执行发布。
          # 如果不存在，它会安静地跳过这些步骤。
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}